# -*- mode: ruby -*-
# vi: set ft=ruby :

$init = <<-SHELL
apt-get update
apt-get install -y wget build-essential flex bison libncurses5-dev libreadline-dev

# Install FRR
# wget -q https://github.com/FRRouting/frr/releases/download/frr-6.0.2/frr_6.0.2-0.ubuntu18.04.1_amd64.deb
# apt-get install -y ./frr_6.0.2-0.ubuntu18.04.1_amd64.deb
# rm ./frr_6.0.2-0.ubuntu18.04.1_amd64.deb
# sed -i 's/zebra=no/zebra=yes/g' /etc/frr/daemons
# systemctl restart frr.service

# Install bird
wget -q ftp://bird.network.cz/pub/bird/bird-2.0.3.tar.gz
tar -zxf bird-2.0.3.tar.gz
(
  cd bird-2.0.3
  ./configure
  make
  make install
)
rm bird-2.0.3.tar.gz
rm -r bird-2.0.3
cp /vagrant/bird.service /lib/systemd/system/bird.service
systemctl daemon-reload

sed -i -e '/^#net.ipv4.ip_forward=1/s/#//' /etc/sysctl.conf
sed -i -e '/^#net.ipv6.conf.all.forwarding=1/s/#//' /etc/sysctl.conf
sysctl --system
/vagrant/update.sh

SHELL

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 1024
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end
  config.vm.define "rtr1" do |rtr|
    config.vm.hostname = "rtr1"
    rtr.vm.network "private_network", ip: "10.1.0.10"
    rtr.vm.network "private_network", ip: "10.0.12.10", virtualbox__intnet: "net12"
    rtr.vm.network "private_network", ip: "10.0.13.10", virtualbox__intnet: "net13"
    config.vm.provision "shell", inline: $init
  end
  config.vm.define "rtr2" do |rtr|
    config.vm.hostname = "rtr2"
    rtr.vm.network "private_network", ip: "10.1.0.20"
    rtr.vm.network "private_network", ip: "10.0.12.20", virtualbox__intnet: "net12"
    rtr.vm.network "private_network", ip: "10.0.24.20", virtualbox__intnet: "net24"
    config.vm.provision "shell", inline: $init
  end
  config.vm.define "rtr3" do |rtr|
    config.vm.hostname = "rtr3"
    rtr.vm.network "private_network", ip: "10.1.0.30"
    rtr.vm.network "private_network", ip: "10.0.13.30", virtualbox__intnet: "net13"
    rtr.vm.network "private_network", ip: "10.0.34.30", virtualbox__intnet: "net34"
    config.vm.provision "shell", inline: $init
  end
  config.vm.define "rtr4" do |rtr|
    config.vm.hostname = "rtr4"
    rtr.vm.network "private_network", ip: "10.1.0.40"
    rtr.vm.network "private_network", ip: "10.0.24.40", virtualbox__intnet: "net24"
    rtr.vm.network "private_network", ip: "10.0.34.40", virtualbox__intnet: "net34"
    config.vm.provision "shell", inline: $init
  end
end
