# -*- mode: ruby -*-
# vi: set ft=ruby :

$install_rtr = <<-SHELL
apt-get update
apt-get install -y wget

wget -q https://github.com/FRRouting/frr/releases/download/frr-6.0.2/frr_6.0.2-0.deb9u1_amd64.deb
apt-get install -y ./frr_6.0.2-0.deb9u1_amd64.deb
rm ./frr_6.0.2-0.deb9u1_amd64.deb
sed -i 's/bgpd=no/bgpd=yes/g' /etc/frr/daemons
systemctl restart frr.service
SHELL

$install_ctrl = <<-SHELL
apt-get update
apt-get install -y wget

wget -q https://github.com/osrg/gobgp/releases/download/v1.33/gobgp_1.33_linux_amd64.tar.gz
tar -zxf gobgp_1.33_linux_amd64.tar.gz
mv gobgpd /usr/local/bin
mv gobgp /usr/local/bin
rm ./gobgp_1.33_linux_amd64.tar.gz
rm ./LICENSE
rm ./README.md
cp /vagrant/gobgpd.service /etc/systemd/system
systemctl daemon-reload
systemctl enable gobgpd.service
systemctl start gobgpd.service
SHELL

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 1024
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end
  config.vm.define "ctrl1" do |ctrl|
    config.vm.hostname = "ctrl1"
    ctrl.vm.network "private_network", ip: "10.1.10.2", virtualbox__intnet: "internal1"
    ctrl.vm.provision "shell", inline: $install_ctrl
  end
  config.vm.define "rtr1" do |rtr|
    config.vm.hostname = "rtr1"
    rtr.vm.network "private_network", ip: "10.1.12.1", virtualbox__intnet: "net12"
    rtr.vm.network "private_network", ip: "10.1.10.1", virtualbox__intnet: "internal1"
    rtr.vm.provision "shell", inline: $install_rtr
  end
  config.vm.define "rtr2" do |rtr|
    config.vm.hostname = "rtr2"
    rtr.vm.network "private_network", ip: "10.1.12.2", virtualbox__intnet: "net12"
    rtr.vm.network "private_network", ip: "10.1.23.1", virtualbox__intnet: "net23"
    rtr.vm.network "private_network", ip: "10.1.20.1", virtualbox__intnet: "internal2"
    rtr.vm.provision "shell", inline: $install_rtr
  end
  config.vm.define "rtr3" do |rtr|
    config.vm.hostname = "rtr3"
    rtr.vm.network "private_network", ip: "10.1.23.2", virtualbox__intnet: "net23"
    rtr.vm.network "private_network", ip: "10.1.30.1", virtualbox__intnet: "internal3"
    rtr.vm.provision "shell", inline: $install_rtr
  end
end
