# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = 4096
    vb.cpus = 2
    vb.customize ["modifyvm", :id, "--audio", "none"]
  end
  config.vm.define "rtr1" do |rtr|
    rtr.vm.network "private_network", ip: "10.1.0.10"
    rtr.vm.network "private_network", ip: "10.0.12.10", virtualbox__intnet: "net12"
    rtr.vm.network "private_network", ip: "10.0.13.10", virtualbox__intnet: "net13"
    rtr.vm.network "private_network", ip: "10.0.15.10", virtualbox__intnet: "net15"
    optional = <<-SHELL
    cp /vagrant/rtr1.conf /etc/frr/frr.conf
    systemctl restart frr.service
    SHELL
    ShellConf(rtr, 'rtr1', optional)
  end
  config.vm.define "rtr2" do |rtr|
    rtr.vm.network "private_network", ip: "10.1.0.20"
    rtr.vm.network "private_network", ip: "10.0.12.20", virtualbox__intnet: "net12"
    rtr.vm.network "private_network", ip: "10.0.24.20", virtualbox__intnet: "net24"
    optional = <<-SHELL
    cp /vagrant/rtr2.conf /etc/frr/frr.conf
    systemctl restart frr.service
    SHELL
    ShellConf(rtr, 'rtr2', optional)
  end
  config.vm.define "rtr3" do |rtr|
    rtr.vm.network "private_network", ip: "10.1.0.30"
    rtr.vm.network "private_network", ip: "10.0.13.30", virtualbox__intnet: "net13"
    rtr.vm.network "private_network", ip: "10.0.34.30", virtualbox__intnet: "net34"
    optional = <<-SHELL
    cp /vagrant/rtr3.conf /etc/frr/frr.conf
    systemctl restart frr.service
    SHELL
    ShellConf(rtr, 'rtr3', optional)
  end
  config.vm.define "rtr4" do |rtr|
    rtr.vm.network "private_network", ip: "10.1.0.40"
    rtr.vm.network "private_network", ip: "10.0.24.40", virtualbox__intnet: "net24"
    rtr.vm.network "private_network", ip: "10.0.34.40", virtualbox__intnet: "net34"
    optional = <<-SHELL
    cp /vagrant/rtr4.conf /etc/frr/frr.conf
    systemctl restart frr.service
   SHELL
    ShellConf(rtr, 'rtr4', optional)
  end
  config.vm.define "rtr5" do |rtr|
    rtr.vm.network "private_network", ip: "10.1.0.50"
    rtr.vm.network "private_network", ip: "10.0.15.50", virtualbox__intnet: "net15"
    optional = <<-SHELL
    cp /vagrant/rtr5.conf /etc/frr/frr.conf
    systemctl restart frr.service
    SHELL
    ShellConf(rtr, 'rtr5', optional)
  end
end

def ShellConf(config, name, optional)
  config.vm.provision "shell", inline: <<-SHELL
  apt-get update
  apt-get install -y wget

  # Install FRR
  wget -q https://github.com/FRRouting/frr/releases/download/frr-6.0/frr_6.0-1.ubuntu16.04+1_amd64.deb
  apt-get install -y ./frr_6.0-1.ubuntu16.04+1_amd64.deb
  rm ./frr_6.0-1.ubuntu16.04+1_amd64.deb
  cp /vagrant/daemons.frr /etc/frr/daemons
  systemctl restart frr.service

  #{optional}
  SHELL
end
